version: '3.2'

services:
  cert-generator:
    image: kamatama41/test-cert-generator
    # build: {context: .}
    volumes:
      - ./tmp/work:/root/work
      - ./tmp/ca:/root/ca
    environment:
      SERVER_COMMON_NAME: mydomain.com
      SERVER_P12_PASSWORD: abcdefg
      CLIENT_COMMON_NAME: myclient
      CLIENT_P12_PASSWORD: hijklmn
