#!/usr/bin/env bash
#####
# ref: https://jamielinux.com/docs/openssl-certificate-authority/
#####

set -eu

private_key_password=${PRIVATE_KEY_PASSWORD:-p@ssw0rd}
server_p12_password=${SERVER_P12_PASSWORD:-p@ssw0rd}
client_p12_password=${CLIENT_P12_PASSWORD:-p@ssw0rd}
server_common_name=${SERVER_COMMON_NAME:-example.com}
client_common_name=${CLIENT_COMMON_NAME:-client}

rm -rf /root/ca/* && mkdir -p /root/ca/intermediate
rm -rf /root/work/*
cd /root/ca
cp /root/openssl_ca.cnf openssl.cnf
cp /root/openssl_intermediate.cnf intermediate/openssl.cnf

## https://jamielinux.com/docs/openssl-certificate-authority/create-the-root-pair.html
mkdir certs crl newcerts private
chmod 700 private
touch index.txt
echo 1000 > serial

openssl genrsa -passout pass:${private_key_password} -aes256 -out private/ca.key.pem 4096
openssl req -passin pass:${private_key_password} -config openssl.cnf \
  -key private/ca.key.pem -new -x509 -days 7300 -sha256 \
  -extensions v3_ca -out certs/ca.cert.pem <<INPUT
GB
England

Alice Ltd
Alice Ltd Certificate Authority
Alice Ltd Root CA

INPUT
chmod 444 certs/ca.cert.pem

## https://jamielinux.com/docs/openssl-certificate-authority/create-the-intermediate-pair.html
cd /root/ca/intermediate
mkdir certs crl csr newcerts private p12
chmod 700 private
touch index.txt
echo 1000 > serial
echo 1000 > /root/ca/intermediate/crlnumber

cd /root/ca
openssl genrsa -passout pass:${private_key_password} -aes256 -out intermediate/private/intermediate.key.pem 4096
chmod 400 intermediate/private/intermediate.key.pem

cd /root/ca
openssl req -passin pass:${private_key_password} -config intermediate/openssl.cnf \
  -new -sha256 -key intermediate/private/intermediate.key.pem \
  -out intermediate/csr/intermediate.csr.pem <<INPUT
GB
England

Alice Ltd
Alice Ltd Certificate Authority
Alice Ltd Intermediate CA

INPUT

openssl ca -passin pass:${private_key_password} -config openssl.cnf \
  -extensions v3_intermediate_ca -days 3650 -notext \
  -md sha256 -in intermediate/csr/intermediate.csr.pem \
  -out intermediate/certs/intermediate.cert.pem <<INPUT
y
y
INPUT

cat intermediate/certs/intermediate.cert.pem certs/ca.cert.pem > intermediate/certs/ca-chain.cert.pem
chmod 444 intermediate/certs/ca-chain.cert.pem

## https://jamielinux.com/docs/openssl-certificate-authority/sign-server-and-client-certificates.html
function signCertificate() {
  common_name=${1}
  days=${2}
  cert_type=${3}
  p12_password=${4}

  cd /root/ca
  openssl genrsa -aes256 -passout pass:${private_key_password} -out intermediate/private/${common_name}.key.pem 2048
  chmod 400 intermediate/private/${common_name}.key.pem

  addext_opt=
  if [ "${cert_type}" = "server_cert" ]; then
    addext_opt="-addext 'subjectAltName = DNS:${common_name}'"
  fi

  cd /root/ca
  openssl req -passin pass:${private_key_password} -config intermediate/openssl.cnf \
    -key intermediate/private/${common_name}.key.pem \
    -addext "subjectAltName = DNS:${common_name}" \
    -new -sha256 -out intermediate/csr/${common_name}.csr.pem <<INPUT
US
California
Mountain View
Alice Ltd
Alice Ltd Web Services
${common_name}

INPUT

  cd /root/ca
  openssl ca -passin pass:${private_key_password} -config intermediate/openssl.cnf \
    -extensions ${cert_type} -days ${days} -notext -md sha256 \
    -in intermediate/csr/${common_name}.csr.pem \
    -out intermediate/certs/${common_name}.cert.pem <<INPUT
y
y
INPUT
  chmod 444 intermediate/certs/${common_name}.cert.pem

  # Generate P12 file
  openssl pkcs12 -export -out /root/ca/intermediate/p12/${common_name}.p12 \
    -in /root/ca/intermediate/certs/${common_name}.cert.pem \
    -inkey /root/ca/intermediate/private/${common_name}.key.pem \
    -passin pass:${private_key_password} -passout pass:${p12_password}
}

signCertificate ${server_common_name} 3650 server_cert ${server_p12_password}
signCertificate ${client_common_name} 3650 usr_cert ${client_p12_password}

# Copy ca-chain and P12 files into working directory
cp /root/ca/intermediate/p12/* \
  /root/ca/intermediate/certs/ca-chain.cert.pem \
  /root/ca/intermediate/certs/${server_common_name}.cert.pem \
  /root/ca/intermediate/certs/${client_common_name}.cert.pem \
  /root/work
